import {
  Type,
  ImageIcon,
  Heading2,
  Grid3X3,
  ArrowDownFromLine,
  Minus,
  Maximize,
  Tag,
  User,
  Columns3,
  LayoutGrid,
} from 'lucide-react';

export const BLOCK_META: Record<string, { label: string; Icon: typeof Type }> = {
  text: { label: 'Text', Icon: Type },
  heading: { label: 'Heading', Icon: Heading2 },
  image: { label: 'Image', Icon: ImageIcon },
  gallery: { label: 'Gallery', Icon: Grid3X3 },
  spacer: { label: 'Spacer', Icon: ArrowDownFromLine },
  divider: { label: 'Divider', Icon: Minus },
  'hero-image': { label: 'Hero Image', Icon: Maximize },
  'work-title': { label: 'Work Title', Icon: Tag },
  'work-metadata': { label: 'Author/Email', Icon: User },
  'work-layout-config': { label: 'Layout Config', Icon: Grid3X3 },
  'layout-row': { label: 'Row Layout', Icon: Columns3 },
  'layout-grid': { label: 'Grid Layout', Icon: LayoutGrid },
  'image-row': { label: 'Image Row', Icon: Columns3 },
  'image-grid': { label: 'Image Grid', Icon: LayoutGrid },
};
